# Generated by Django 5.2.7 on 2025-11-17 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255, verbose_name='ID сесії')),
                ('cart_start', models.DateTimeField(verbose_name='Дата створення')),
                ('cart_stop', models.DateTimeField(verbose_name='Дата закриття')),
                ('prod_list', models.JSONField(verbose_name='Список товарів')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='ID сесії')),
                ('cart_start', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('cart_stop', models.DateTimeField(blank=True, null=True, verbose_name='Дата закриття')),
            ],
        ),
        migrations.CreateModel(
            name='CartStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код статуса')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_start', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
                ('item_del', models.DateTimeField(blank=True, null=True, verbose_name='Дата видалення')),
                ('item_qtty', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Загальна вартість')),
                ('id_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart', verbose_name='Посилання на кошик')),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.product', verbose_name='Посилання на продукт')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cart.cartstatus', verbose_name='Статус кошика'),
        ),
    ]
