# Generated by Django 5.2.7 on 2025-11-04 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код категорії')),
                ('name', models.CharField(max_length=255, verbose_name='Назва категорії')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис категорії')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код виробника')),
                ('name', models.CharField(max_length=255, verbose_name='Назва виробника')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис виробника')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, unique=True, verbose_name='Номер заказу')),
                ('odate', models.DateField(auto_now_add=True, verbose_name='Дата заказу')),
                ('orderprice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Загальна вартість')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код товару')),
                ('name', models.CharField(max_length=255, verbose_name='Назва товару')),
                ('short_descr', models.CharField(max_length=255, verbose_name='Короткий опис')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Повний опис')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='api.category')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='api.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdate', models.DateField(verbose_name='Дата встановлення ціни')),
                ('pprice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('qtty', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Кількість таких товарів у наявності')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtty', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Кількість цього товару у замовленні')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='api.OrderProduct', to='api.product'),
        ),
    ]
